### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [aelvan/mailchimp-subscribe-craft#75]
HiAelvan,

It looks like your pluginisn't compatible with `PHP 7.0`. We're running a `Craft CMS 2.7.5` and getting a `Parameter must be an array or an object that implements Countable` error in the Response:

```
<h1>PHP Error [500]</h1>
<p>count(): Parameter must be an array or an object that implements Countable (APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:67)</p>
<pre>#0 APP-PROJECT-FOLDER/core/app/etc/errors/ErrorHandler.php(184): Craft\ErrorHandler->handleError()
#1 APP-PROJECT-FOLDER/core/app/framework/base/CErrorHandler.php(133): Craft\ErrorHandler->handleError()
#2 APP-PROJECT-FOLDER/core/app/framework/base/CApplication.php(834): Craft\ErrorHandler->handle()
#3 APP-PROJECT-FOLDER/core/app/etc/web/WebApp.php(694): Craft\WebApp->handleError()
#4 unknown(0): Craft\WebApp->handleError()
#5 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(67): count()
#6 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(107): GuzzleHttp\Handler\CurlFactory->release()
#7 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): finish()
#8 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#9 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\{closure}()
#10 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): GuzzleHttp\Handler\{closure}()
#11 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#12 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): GuzzleHttp\{closure}()
#13 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
#14 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\{closure}()
#15 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Client.php(268): GuzzleHttp\HandlerStack->__invoke()
#16 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer()
#17 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync()
#18 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request()
#19 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/pacely/mailchimp-apiv3/src/Mailchimp.php(150): GuzzleHttp\Client->__call()
#20 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/vendor/pacely/mailchimp-apiv3/src/Mailchimp.php(79): Mailchimp\Mailchimp->makeRequest()
#21 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/services/MailchimpSubscribeService.php(192): Mailchimp\Mailchimp->request()
#22 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/services/MailchimpSubscribeService.php(58): Craft\MailchimpSubscribeService->_getMemberByEmail()
#23 APP-PROJECT-FOLDER/plugins/mailchimpsubscribe/controllers/MailchimpSubscribe_ListController.php(34): Craft\MailchimpSubscribeService->subscribe()
#24 APP-PROJECT-FOLDER/core/app/framework/web/actions/CInlineAction.php(49): Craft\MailchimpSubscribe_ListController->actionSubscribe()
#25 APP-PROJECT-FOLDER/core/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#26 APP-PROJECT-FOLDER/core/app/framework/web/CController.php(286): Craft\MailchimpSubscribe_ListController->runAction()
#27 APP-PROJECT-FOLDER/core/app/framework/web/CController.php(265): Craft\MailchimpSubscribe_ListController->runActionWithFilters()
#28 APP-PROJECT-FOLDER/core/app/framework/web/CWebApplication.php(282): Craft\MailchimpSubscribe_ListController->run()
#29 APP-PROJECT-FOLDER/core/app/etc/web/WebApp.php(837): Craft\WebApp->runController()
#30 APP-PROJECT-FOLDER/core/app/etc/web/WebApp.php(288): Craft\WebApp->_processActionRequest()
#31 APP-PROJECT-FOLDER/core/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#32 APP-PROJECT-FOLDER/core/app/index.php(73): Craft\WebApp->run()
#33 APP-PROJECT-FOLDER/www/index.php(23): require_once()
#34 /Users/mark/.composer/vendor/laravel/valet/server.php(158): require()
</pre>
```

*Update: Upgrading to php 7.2 still doesn't correct the issue*

This error sounds like a common issue for CraftCMS 2 plugins. Is this something you can update?

Thanks for your help and all you do for the community is awesome!

**Comment by aelvan** [comment]
PR #78 should fix this.
